### PR TITLE
Update config.php.example

### PR DESCRIPTION
**Pull request by Juraganet**
Connect using api_identifier and api_secret.
The username+password+api_secret is no longer working I think

I also propose to modify cron.php file

### CODE REVIEW

**Comment by eksoverzero** [comment]
Thanks, @Juraganet. Is it possible to change them in the rebase branch rather? I just need to do a few more things there for the new releases of WHMCS and then it will go live.

**Comment by Juraganet** [comment]
that is not a problem

**Comment by amaurynieto** [comment]
Amazing @eksoverzero  - If you need tests on this end, or if there is *anything* I can do to help out, let me know. Eager to try this new version out.

**Comment by eksoverzero** [comment]
Added changes to the refactor branch: https://github.com/eksoverzero/whmcs-freeradius/tree/refactor

**Pull request closed without merging**
